// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/actions/perform': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/actions/perform.post').default>>>>
    }
    '/api/assets/buy': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assets/buy.post').default>>>>
    }
    '/api/assets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assets/index.get').default>>>>
    }
    '/api/cron/market-update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/market-update.post').default>>>>
    }
    '/api/economy/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/economy/summary.get').default>>>>
    }
    '/api/events/pending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/events/pending.get').default>>>>
    }
    '/api/events/resolve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/events/resolve.post').default>>>>
    }
    '/api/game/tick': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/game/tick.post').default>>>>
    }
    '/api/loans/active': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/loans/active.get').default>>>>
    }
    '/api/loans/offers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/loans/offers.get').default>>>>
    }
    '/api/market/companies': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/market/companies.get').default>>>>
    }
    '/api/player/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/profile.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}