// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025-12-19 00:08:58
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/swegr/Documents/GitHub/money_printer/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/swegr/Documents/GitHub/money_printer/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/swegr/Documents/GitHub/money_printer/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/swegr/Documents/GitHub/money_printer/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/swegr/Documents/GitHub/money_printer/app/plugins/**/*.{js,ts,mjs}","C:/Users/swegr/Documents/GitHub/money_printer/app/composables/**/*.{js,ts,mjs}","C:/Users/swegr/Documents/GitHub/money_printer/app/utils/**/*.{js,ts,mjs}","C:/Users/swegr/Documents/GitHub/money_printer/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/swegr/Documents/GitHub/money_printer/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/swegr/Documents/GitHub/money_printer/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/swegr/Documents/GitHub/money_printer/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;